Planet of Lana TAA fix
illusion0001/Windows-Game-Patches pull request #4
Opened 2023-07-15 11:45 UTC by TL431

Rename dinput8.dll to d3d11.dll and copy d3d11.ini in the game folder. The setting DontLoadFromDllMain=0 in d3d11.ini is mandatory to make the game load the ASI patch without crashing.

2023-07-15 12:42 UTC, illusion0001 requested changes
Needs to be added to the solution file for CI to build, you can do that by opening the sln file and add the project to it

2023-07-15 17:32 UTC, TL431 commented
So should I change the definitions 
_PROJECT_NAME -> PROJECT_NAME 
_PROJECT_LOG_PATH -> PROJECT_LOG_PATH 
to make the compilation to succeed? 

All the fixes except BFV use the convention with the underscore (_PROJECT_NAME and _PROJECT_LOG_PATH)

2023-07-17 00:21 UTC, illusion0001 approved these changes

2023-07-17 00:22 UTC, illusion0001 commented
Fixed, no idea why it didn't work the first time

2023-07-17 00:26 UTC, merged